# Identity metadata from SonarCloud onboarding
sonar.projectKey=HlibBondarev_TTA-frontend
sonar.organization=hlibbondarev
sonar.projectName=TTA-frontend
sonar.projectVersion=1.0

# Path to the source and test directories
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/setup.ts

# Exclusions from analysis
sonar.exclusions=node_modules/**,dist/**,coverage/**,vite.config.ts,vitest.config.ts

# Exclusions from test coverage analysis
sonar.coverage.exclusions=src/db/seed.ts, src/main.tsx, src/vite-env.d.ts

# Path to the test execution coverage report in LCOV format
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Standard source file encoding
sonar.sourceEncoding=UTF-8